<div id="cajaSobre">
    <div class="contentBox">
        <b>PRESENTACIÓN INTERMODELS</b><br>
        (GRUPO INTERMUSICAL.ES)<br><br>
        <p>
            Siguiendo la pauta de innovaciones de nuestro grupo intermusical... el pasado día 25 de Octubre de 2010 tuvo lugar la presentación y primer casting de nuestra nueva empresa Intermodels.es.
            <br><br>
            El evento se celebró con gran éxito en el estudio Shoot-115 de Barcelona con la participación de un elenco de 30 jóvenes que mostraron su bien hacer ante las cámaras como preámbulo a futuras intervenciones en el complejo ámbito de los medios de la moda, publicidad y propaganda.
            <br><br>
            Y es en este contexto que Intermodels tiene como objetivo básico lograr la presentación  de sus participantes a través del portal web para la prestación de sus servicios como modelos en eventos diversos, desfiles de pasarelas, reportajes fotográficos o televisivos, como azafatas de congresos o reuniones empresariales y cualquier otro evento que reúna las condiciones requeridas al cumplimiento de nuestros objetivos.
            <br><br>
            Para ello, nuestro esfuerzo esta dirigido hacia el logro de una gestión  exitosa con la doble finalidad de cumplir nuestro compromiso ante nuestros propios colaboradores y futuros clientes.
            <br><br>
            Si quieres formar parte del maravilloso equipo de intermodels envíanos un mensaje a: info@<span class="mrHide">null</span>intermodels.es
            <br><br>
            Gracias a todos por vuestra confianza.
            <br><br>
            Luis Alvero<br>
            <i>Fundador y Director General</i>
        </p>
    </div>
</div>