<div id="cajaPerfiles">
	<br/><br/>
	<table align="center">
		<tr>
			<td align="center">Chicos</td>
			<td align="center">Chicas</td>
		</tr>
		<tr>
			<td><a href="<?php echo $this->url(array(), 'PerfilesChicos') ?>"><img src="images/fronted/intermodels_chicos.jpg" border="0"/></a></td>
			<td><a href="<?php echo $this->url(array(), 'PerfilesChicas') ?>"><img src="images/fronted/intermodels_chicas.jpg" border="0"/></a></td>
		</tr>
	</table>
	<br/>
	<center>
	Para contrataci&oacute;n directa, enviar un correo a info@<span class="mrHide">null</span>intermodels.es o llamar al (+34) 647 291 379.
	</center>

</div>