<div id="cajaPolitica">
	<div class="contentBox">
<b>Pol&iacute;tica de privacidad</b>
<br/><br/>
En tan s&oacute;lo 8 meses nos hemos posicionado como la gu&iacute;a musical alternativa con m&aacute;s de 400.000 usuarios &uacute;nicos mensuales (informaci&oacute;n en alexa.com).
<br/><br/>
El grupo intermusical.es el cual intermnodels.es forma parte del mismo, es el nuevo proyecto de Luis Alvero acompa&ntilde;ado por j&oacute;venes emprendedores del mundo musical y de la moda.
<br/><br/>
La presente pol&iacute;tica de protecci&oacute;n de datos regula el acceso y el uso del servicio del sitio web intermusical.es y intermodels.es (en adelante, el "Sitio Web"), que intermusical.es pone a disposici&oacute;n de los usuarios de Internet interesados en sus servicios y contenidos (en adelante, los "Usuarios").
<br/><br/>
De conformidad con lo establecido por la Ley Org&aacute;nica 15/1999, de 13 de diciembre, de Protecci&oacute;n de Datos de Car&aacute;cter Personal (en adelante, LOPD), intermusical.es titular del sitio web, informa al usuario de este sitio de la existencia de un fichero automatizado de datos de car&aacute;cter personal creado por intermusical.es y bajo su responsabilidad con la finalidad de realizar el mantenimiento y gesti&oacute;n del servicio de comunidad virtual de los usuarios de intermusical.es que han sido registrados a trav&eacute;s de los formularios electr&oacute;nicos del Sitio.
<br/><br/>
Los datos facilitados por los usuarios son incorporados en un fichero en el servidor de intermusical.es. Como web privada no es necesario la inscripci&oacute;n de la misma en el Registro de Protecci&oacute;n de Datos.
<br/><br/>
En todo momento, el Usuario podr&aacute; acceder, rectificar, cancelar sus datos de car&aacute;cter personal u oponerse al tratamiento de los mismos, mediante petici&oacute;n por escrito a tal efecto, dirigida a intermusical.es, Gran V&iacute;a Carles III 91, Barcelona (Barcelona).
<br/><br/>
<b>X. Alertas y comunicaciones electr&oacute;nicas</b>
<br/><br/>
La cumplimentaci&oacute;n y env&iacute;o de los formularios electr&oacute;nicos de intermusical.es, supone el consentimiento expreso del usuario al env&iacute;o de las siguientes comunicaciones electr&oacute;nicas, salvo que se indique lo contrario:
<br/><br/>
- Boletin semanal de novedades: intermusical.es enviar&aacute; con periodicidad mensual un correo electr&oacute;nico informando a los usuarios de las novedades de los conciertos de los artistas de intermusical.es o de los eventos organizados por intermusical.es directamente.
<br/><br/>
intermusical.es facilita el email info@intermusical.es a los usuarios que lo soliciten puedan pedir la modificaci&oacute;n o eliminaci&oacute;n de estos servicios.
<br/><br/>
intermusical.es no utilizar&aacute; el email de sus usuarios para otro fin que no sea los descritos en este apartado.
<br/><br/>
<b>X. Cookies</b>
<br/><br/>
Las cookies son peque&ntilde;os ficheros de datos que se alojan en el terminal del Usuario visitante del Sitio Web y que contienen cierta informaci&oacute;n de la visita a la p&aacute;gina. El presente Sitio Web utiliza cookies &uacute;nicamente con el fin de facilitar la navegaci&oacute;n de los Usuarios y sin que en ning&uacute;n caso sea posible asociar tales cookies a los datos personales concretos de los Usuarios ni identificar a &eacute;stos a trav&eacute;s de aqu&eacute;llas.
<br/><br/>
<b>X. Foros</b>
<br/><br/>
El equipo de intermusical.es no se hace responsable de los comentarios u opiniones y dem&aacute;s creados por los usuari@s de intermusical.es. El equipo tiene el derecho de eliminar cualquier comentario que est&eacute; fuera de la legalidad de protecci&oacute;n de datos y/o utilizaci&oacute;n de datos personales.
<br/><br/>
<b>x. Acerca de utilizaci&oacute;n de contenido web.</b>
<br/><br/>
* GoogleMaps API, para mostrar la localizaci&oacute;n de las salas de conciertos.
* La base de datos de artistas y albumes abierta en intermusical.es.
* La informaci&oacute;n de artistas relacionados, Tags, Noticias las obtenemos del servicio Web de nvivo.es, elmundo.es, terra.es, abastodenoticias.com.
* Los videos de artistas y actuaciones los obtenemos de Youtube.com
* Algunas fotos de conciertos se obtienen a trav&eacute;s de myspace.com, facebook.com o directamente de las webs de los Artistas debidamente aceptados por los mismos.
*Las fotografias que suben los usuarios en su perfil en intermusical.es es privada y no es responsabilidad de intermusical.es.
<br/><br/>
intermusical.es se reserva el derecho de modificar su Pol&iacute;tica de Protecci&oacute;n de Datos de acuerdo con la legislaci&oacute;n aplicable en cada momento. Cualquier modificaci&oacute;n de la Pol&iacute;tica de Protecci&oacute;n de Datos ser&aacute; publicada en el Sitio.
	</div>
</div>