<div id="cajaServicios">
	<div class="contentBox">
<b>Eres Modelo, Gogo, Azafata o Camarera y quieres promocionarte en intermodels.es, que necesitamos?</b>
<br/>
<ul>
	<li>Biograf&iacute;a Art&iacute;stica (Formato word o pdf)</li>
	<li>Fotograf&iacute;as Varias (Formatos: jpg y png, Medidas: Todas las posibles)</li>
	<li>Medidas, Color del Pelo, Intereses, Gustos, Tendencias (Formato word o pdf)</li>
	<li>Datos de contacto personal (Email y Tel&eacute;fono)</li>
</ul>
Y lo m&aacute;s importante, tener vocaci&oacute;n en este amplio y dif&iacute;cil mundo el cual te formar&aacute;n un gran equipo de t&eacute;cnicos...
<br/><br/>

<b>Qu&eacute; servicios te ofrecemos desde intermodels.es?</b>
<br/>
<ul>
	<li>Mejora del posicionamiento del perfil de trabajo en internet
	<li>Alta del perfil (ficha t&eacute;cnica) en la secci&oacute;n PERFILES en intermodels.es
	<li>Difusi&oacute;n de tu imagen en todo el &aacute;mbito promocional online
	<li>Creaci&oacute;n de un facebook experto (incluyendo la b&uacute;squeda de fans)
	<li>B&uacute;squeda de trabajos a nivel nacional y internacional
	<li>B&uacute;squeda de entrevistas en radios y televisiones locales y nacionales
	<li>Soporte en todas las contrataciones de nuestros colaboradores (moda, pasarelas, imagen, discotecas, etc)
	<li>Env&iacute;o de emails con las actividades a los usuarios del grupo intermusical y redes sociales
</ul>
<br/>
*El grupo intermusical, la cual, intermodels.es forma parte, actualmente supera el mill&oacute;n de seguidores a nivel internacional (Espa&ntilde;a, Francia, Brasil, Colombia, M&eacute;xico, Venezuela, Portugal, etc...).
<br/><br/>
No esperes m&aacute;s, contacta ya con nuestro equipo de t&eacute;cnicos en info@<span class="mrHide">null</span>intermodels.es e inf&oacute;rmate de las mejores condiciones que te podemos ofrecer para acceder a formar parte del elenco de intermodels, y no olvides que intermodels.es es un portal promocional con mucho &eacute;xito, pero nunca dejar&aacute; la l&iacute;nea de la Alternativa a las dem&aacute;s agencias Espa&ntilde;olas...
	</div>
</div>