<div id="footer">
  <div id="footcont">
    <ul>
        <li><a href="<?php echo $this->url(array(), 'Home') ?>">Inicio</a></li>
		<!--<li><a href="<?php echo $this->url(array(), 'Home') ?>">Agenda</a></li>-->
        <li><a href="<?php echo $this->url(array(), 'About') ?>">Sobre Intermodels</a></li>
        <li><a href="<?php echo $this->url(array(), 'Perfiles') ?>">Perfiles</a></li>
    </ul>
    <ul>
        <li><a href="<?php echo $this->url(array(), 'Privacidad') ?>">Privacidad</a></li>
        <li><a href="<?php echo $this->url(array(), 'Services') ?>">Servicios</a></li>
        <!--<li><a href="<?php echo $this->url(array(), 'Home') ?>">Galeria</a></li>-->
        <li><a href="<?php echo $this->url(array(), 'Contact') ?>">Contacto</a></li>
    </ul>
    <ul>
        <li>info@<span class="mrHide">null</span>intermodels.es</li>
        <li>Telf. (+34) 647 291 379</li>
	<li>Plaza Daniel Sanahuja 4, 2o 2a</li>
	<li>08201 Sabadell (Barcelona)</li>
    </ul>
    <p class="kromatick footlogo"><a href="http://kromatick.com/" title="Kromatick, Tu Nueva Agencia Creativa" target="_blank">Diseño:</a></p>
    <p class="derechos">
        INTERMODELS es una marca del grupo <a href="http://intermusical.es/" title="" target="_blank">INTERMUSICAL</a><br/>
	&copy; 2010 Intermodels.es | Todos los derechos reservados
    </p>
  </div>
</div>