<div id="menu">
    <div class="linkmenu"><a href="<?php echo $this->url(array(), 'Home') ?>" class="fade">Inicio</a></div> ·
    <!--<div class="linkmenu"><a href="<?php echo $this->url(array(), 'Home') ?>" class="fade">Agenda</a></div> ·-->
    <div class="linkmenu"><a href="<?php echo $this->url(array(), 'About') ?>" class="fade">Sobre Intermodels</a></div> ·
    <div class="linkmenu"><a href="<?php echo $this->url(array(), 'Perfiles') ?>" class="fade">Perfiles</a></div> ·
    <div class="linkmenu"><a href="<?php echo $this->url(array(), 'Services') ?>" class="fade">Servicios</a></div> ·
    <!--<div class="linkmenu"><a href="<?php echo $this->url(array(), 'Home') ?>" class="fade">Galeria</a></div> ·-->
    <div class="linkmenu"><a href="<?php echo $this->url(array(), 'Contact') ?>" class="fade">Contacto</a></div>
</div>