<?php

/**
 * Evento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Kromatick
 * @subpackage Intermodels
 * @author     Neozeratul <neozeratul@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Evento extends BaseEvento
{
    public static function findEventos()
    {
        return Doctrine_Core::getTable('Evento')
               ->findAll();
    }

    public static function findEvento($evento)
    {
        return Doctrine_Core::getTable('Evento')
               ->findOneById($evento);
    }

    public static function findEventosActive()
    {
        return Doctrine_Core::getTable('Evento')
               ->findByStatus(true);
    }

    public function nuevo()
    {
        $this->save();
        $picasa = new Neo_Gdata_Photo();
        $album  = $picasa->addAlbum($this->id);
        $this->album_id = $album->getGphotoId();
        $this->save();
    }

    public function addPhoto($foto)
    {
        $picasa = new Neo_Gdata_Photo();
        $resultPhoto = $picasa->insertPhoto($this->album_id, $foto);
        $this->Photos[] = Photo::setPhoto($resultPhoto);
        $this->save();
    }

    public function delete()
    {
        $q = Doctrine_Query::create()
            ->delete('EventoPhoto')
            ->addWhere('evento_id = ?', $this->id);
        $deleted = $q->execute();
        parent::delete();
    }
}