<?php

/**
 * Galeria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Kromatick
 * @subpackage Intermodels
 * @author     Neozeratul <neozeratul@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Galeria extends BaseGaleria
{
    public static function findGalerias()
    {
        return Doctrine_Core::getTable('Galeria')
               ->findAll();
    }

    public static function findGaleria($galeria)
    {
        return Doctrine_Core::getTable('Galeria')
               ->findOneById($galeria);
    }

    public static function findGaleriasActive()
    {
        return Doctrine_Core::getTable('Galeria')
               ->findByStatus(true);
    }

    public function nuevo()
    {
        $this->save();
        $picasa = new Neo_Gdata_Photo();
        $album  = $picasa->addAlbum($this->titulo);
        $this->album_id = $album->getGphotoId();
        $this->save();
    }

    public function addPhoto($foto)
    {
        $picasa = new Neo_Gdata_Photo();
        $resultPhoto = $picasa->insertPhoto($this->album_id, $foto);
        $this->Photos[] = Photo::setPhoto($resultPhoto);
        $this->save();
    }

    public function delete()
    {
        $q = Doctrine_Query::create()
            ->delete('GaleriaPhoto')
            ->addWhere('galeria_id = ?', $this->id);
        $deleted = $q->execute();
        parent::delete();
    }
}