<?php

/**
 * Modelo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Kromatick
 * @subpackage Intermodels
 * @author     Neozeratul <neozeratul@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Modelo extends BaseModelo
{
    public static function findModelos()
    {
        return Doctrine_Core::getTable('Modelo')
               ->findAll();
    }

    public static function findModelo($modelo)
    {
        return Doctrine_Core::getTable('Modelo')
               ->findOneById($modelo);
    }

    public static function findModelosActive()
    {
        return Doctrine_Core::getTable('Modelo')
               ->findByStatus(true);
    }

    public static function findModelosChicosActive()
    {
        return Doctrine_Core::getTable('Modelo')
               ->findByStatusAndSexo(true, 'Hombre');
    }

    public static function findModelosChicasActive()
    {
        return Doctrine_Core::getTable('Modelo')
               ->findByStatusAndSexo(true, 'Mujer');
    }

    public function nuevo()
    {
        $this->save();
        $picasa = new Neo_Gdata_Photo();
        $album  = $picasa->addAlbum($this->nombres . ' ' . $this->apellidos);
        $this->album_id = $album->getGphotoId();
        $this->save();
    }

    public function addPhoto($foto)
    {
        $picasa = new Neo_Gdata_Photo();
        $resultPhoto = $picasa->insertPhoto($this->album_id, $foto);
        $this->Photos[] = Photo::setPhoto($resultPhoto);
        $this->save();     
    }

    public function getFotos()
    {
        $picasa = new Neo_Gdata_Photo();
        return $picasa->getPhotos($this->album_id);
    }

     public function delete()
    {
        $q = Doctrine_Query::create()
            ->delete('ModeloPhoto')
            ->addWhere('modelo_id = ?', $this->id);
        $deleted = $q->execute();
        parent::delete();
    }
}