<?php

/**
 * Photo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Kromatick
 * @subpackage Intermodels
 * @author     Neozeratul <neozeratul@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Photo extends BasePhoto
{
    public static function findPhoto($photo)
    {
        return Doctrine_Core::getTable('Photo')
               ->findOneById($photo);
    }

    /**
     * Añade una foto cargada (Zend_Gdata_Photos_PhotoFeed)
     * al modelo Photo.
     *
     * @param  Zend_Gdata_Photos_PhotoEntry          $picasaPhoto
     * @return Photo
     */
    public static function setPhoto($picasaPhoto)
    {
        $foto = new Photo();
        try{
            $original  = $picasaPhoto->getMediaGroup()->getContent();
            $thumbnail = $picasaPhoto->getMediaGroup()->getThumbnail();

            $foto->photo_id    = $picasaPhoto->getGphotoId();
            $foto->original    = $original[0]->getUrl();
            $foto->descripcion = $picasaPhoto->getMediaGroup()->getDescription();
            $foto->thumbnail_1 = $thumbnail[0]->getUrl();
            $foto->thumbnail_2 = $thumbnail[1]->getUrl();
            $foto->thumbnail_3 = $thumbnail[2]->getUrl();
            $foto->save();
            return $foto;
        } catch (Zend_Exception $e){
            
        }
    }

    /**
     * Añade datos de la ultima foto cargda (Zend_Gdata_Photos_PhotoFeed)
     * al modelo Photo.
     *
     * @return Photo
     */
    public static function converseToModel()
    {
        $picasa = new Neo_Gdata_Photo();
        $photo = $picasa->getLastPhotoUpload();
        $foto = new Photo();
        $foto->photo_id    = $photo->getGphotoId();
        $foto->titulo      = $photo->getTitle();
        $foto->descripcion = $photo->getMediaGroup()->getDescription();
        $thumbnail = $photo->getMediaGroup()->getThumbnail();
        $foto->thumbnail_1 = $thumbnail[0]->getUrl();
        $foto->thumbnail_2 = $thumbnail[1]->getUrl();
        $foto->thumbnail_3 = $thumbnail[2]->getUrl();
        $foto->save();
        return $foto;
    }
}