<div id="pageModelo">
    <div class="sg-35">
    <a href="<?php echo $this->url(array(), 'addModelo') ?>">Nuevo Modelo</a>
    <?php
    if($this->modelos->count()){
        echo $this->partial()->setObjectKey('Modelos')
                             ->partial('modelos/listaModelos.phtml', $this->modelos);
        echo $this->paginationControl($this->modelos, 'Sliding', 'modelos/paginationModelo.phtml');
    }else{
        ?><div>No existen Modelos</div><?php
    }
    ?>
    </div>
</div>