<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <div>
        <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
        de <?php echo $this->totalItemCount; ?>
    </div>
    <div>
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
          <a href="<?php echo $this->url(array('page' => $this->first), 'galeriasPage'); ?>">
            First
          </a> |
        <?php else: ?>
          <span class="disabled">First</span> |
        <?php endif; ?>

        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
          <a href="<?php echo $this->url(array('page' => $this->previous), 'galeriasPage'); ?>">
            « Previous
          </a> |
        <?php else: ?>
          <span class="disabled">< Previous</span> |
        <?php endif; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
          <a href="<?php echo $this->url(array('page' => $this->next), 'galeriasPage'); ?>">
            Next »
          </a> |
        <?php else: ?>
          <span class="disabled">Next »</span> |
        <?php endif; ?>

        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
          <a href="<?php echo $this->url(array('page' => $this->last), 'galeriasPage'); ?>">
            Last
          </a>
        <?php else: ?>
          <span class="disabled">Last</span>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>